[package]
name = "test_lulu"
version = "0.1.0"
edition = "2021"
description = "A fun test_lulu game."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
